### ISSUE TITLE
Refactoring affecting `Union` annotations

### ISSUE THREAD

**Issue by somada141** [sourceryai/public#12]
### Issue description or question

Refactoring a snippet seems to have lead to the `Union` annotation being wrapped into a tuple for no good reason.

Before:

```
from typing import Union

def _et(element) -> Union[str, None]:
    """Extracts the element text (ET)."""

    text = None
    if element is not None:
        text = element.text

    if not text:
        text = None
    else:
        text = text.strip()

    return text
```

After:

```
from typing import Union

def _et(element) -> Union[(str, None)]:
    """Extracts the element text (ET)."""

    text = None
    if element is not None:
        text = element.text

    text = None if not text else text.strip()
    return text
```

Note how `Union[str, None]` became `Union[(str, None)]`

### Code editor or IDE name and version

Pycharm v2019.2.1

### OS name and version

OSX 10.14.6

**Comment by somada141** [comment]
Just FYI: noticed the same happening to `Dict[str, str]` annotation

**Comment by Hellebore** [comment]
Thanks for raising - have reproduced.

**Comment by Hellebore** [comment]
Addressed in next release.
