### ISSUE TITLE
Refactoring of a boolean return if statement changes return type

### ISSUE THREAD

**Issue by somada141** [sourceryai/public#13]
### Issue description or question

Before:

```
def sth(somedict):
    if not somedict.get("somekey"):
        return False
    
    return True
```

After:

```
def sth(somedict):
    return somedict.get("somekey")
```

As you can see a check for the existence of a key which is meant to return a boolean is refactored to returning the actual value under the key which could easily be `False`.

### Code editor or IDE name and version

Pycharm v2019.2.1

### OS name and version

OSX 10.14.6

**Comment by Hellebore** [comment]
Good point - maybe we should wrap it in a bool in these cases.

**Comment by Hellebore** [comment]
OK have pushed a fix - should be included in our next version.

**Comment by somada141** [comment]
Awesome 🎉
