### ISSUE TITLE
Suggestion not displaying correctly in PyCharm

### ISSUE THREAD

**Issue by burkesquires** [sourceryai/public#15]
### Issue description or question

Open project, clicked on run in Sourcery plugin and saw an issue. Clicked on the issue, convert loop to list comprehension and I could see that there was a suggestion but perhaps the text was to long as I could not see the correction or suggested test (assuming that what is it). Please see screenshot.

### Code editor or IDE name and version

Pycharm v2019.2.1 Pro

### OS name and version

Windows
OSX - 10.14.6
![Screen Shot 2019-09-12 at 11 40 49 AM (2)](https://user-images.githubusercontent.com/881876/64799804-6da45980-d553-11e9-9412-2830bfa2c06c.png)
![Screen Shot 2019-09-12 at 11 41 31 AM (2)](https://user-images.githubusercontent.com/881876/64799838-77c65800-d553-11e9-9c31-0e6384da60e8.png)

Linux

**Comment by brendanator** [comment]
This is now fixed in the next version of the plugin. Should arrive in the next few days

Thanks for the report!

**Comment by burkesquires** [comment]
Thanks! Great work!
