### ISSUE TITLE
PyCharm plugin process running in the background and throwing errors

### ISSUE THREAD

**Issue by JakubBlaha** [sourceryai/public#16]
### Issue description or question
There is a background process running saying *Sourcery update check complete*, and constantly trowing out error notifications saying the following. The correct API token is entered in the settings. The `certifi` folder is not present.
```
Unable to connect to Sourcery executable: Could not find a suitable TLS CA certificate bundle, invalid path: C:\Users\jakub\AppData\Roaming\sourcery\bin\certifi\cacert.pem
```
![running process indicator](https://user-images.githubusercontent.com/28687156/68228979-a9f5b280-fff6-11e9-8d23-3317f5f6b131.png)
![error notification](https://user-images.githubusercontent.com/28687156/68229116-ea553080-fff6-11e9-860f-6ede6876a564.png)
![spammed up the event log](https://user-images.githubusercontent.com/28687156/68229251-2c7e7200-fff7-11e9-8093-3bc00b9411e7.png)

### Code editor or IDE name and version

Pycharm v2019.2.4

### OS name and version

Windows 10 1903

**Comment by Hellebore** [comment]
Thanks for raising this - it looks like an issue with the version of the plugin that was just released. I've been able to reproduce it.

**Comment by JakubBlaha** [comment]
Actually the TLS CA certificate error has been happening before and I wasn't able to use sourcery because of it.

**Comment by Hellebore** [comment]
I've uploaded a new version of the plugin to the Jetbrains marketplace which should resolve the issue, and hopefully the TLS CA certificate one as well. It might take Jetbrains up to a couple of days to approve it. I will update this issue when they do. In the meantime you could try deleting the sourcery directoy in Appdata/Roaming, which might resolve it manually.

**Comment by Hellebore** [comment]
An upgraded version of the plugin - 0.1.2 - is now available. Could you try installing it and see if it resolves the issues?

**Comment by JakubBlaha** [comment]
I have not tried deleting the sourcery directory, but the new plugin version has resolved the issue. Thanks a lot and keep your amazing work up!
