### ISSUE TITLE
Ignore some refactoring suggestions

### ISSUE THREAD

**Issue by herronelou** [sourceryai/public#17]
### Issue description or question

Is there a way to tell Sourcery (or PyCharm) to ignore certain refactoring suggestions?
It's not that the suggestions are wrong, but sometimes I prefer the way the code reads without the refactoring. I can't seem to find a way to tell Sourcery to stop highlighting this part of the code, so I'm just turning off Sourcery for now.

### Code editor or IDE name and version

Pycharm v2018.1.4 Community Edition

### OS name and version

Linux

**Comment by Hellebore** [comment]
Yes we've been thinking of adding this, but haven't been sure how to implement it.

Would a comment-based system (like mypy/yapf/pylint etc) be too intrusive?
e.g #sourcery disable on the function?

**Comment by herronelou** [comment]
I don't know how doable that would be, but with PyCharm's built in warnings, you can click the lightbulb that shows up and pick "ignore", and decide to ignore this instance of the issue, or all the similar issues in the project. This type of solution that doesn't require to add anything to the code would be ideal for me, already not a fan of all the pylint: disable tags.

Also not sure if doable/practical, but it might be interesting for you guys if there is an option to opt-in to share usage back with you, so that your model can learn from what users decide to ignore.

**Comment by Hellebore** [comment]
I think we're going to provide a way to disable with comments and also do it through Pycharm as you suggest.

**Comment by Hellebore** [comment]
Disable with `# sourcery off` is going into the next release. Hopefully will also have a way to do it in pycharm available at some point next week.

**Comment by Hellebore** [comment]
Update has just gone live (you need to update the plugin).
We now have the # sourcery off comment flag, and also disable/enable options directly in Pycharm.
We don't yet have the option to disable all similar issues, but have added it to our roadmap.
