### ISSUE TITLE
Failed to download Sourcery: Downloaded version returns error

### ISSUE THREAD

**Issue by smilicev** [sourceryai/public#18]
### Issue description or question
I have installed Sourcery plugin, and when it starts to download I got an error:
`Failed to download Sourcery: Downloaded version returns error`
I have tried turning off pycharm, and restarted computer, uninstalled Sourcery plugin, and installed it again. End result is always the same.

### Code editor or IDE name and version

Pycharm 2019.3

### OS name and version
Linux, 5.0.21-1

**Comment by Hellebore** [comment]
Thanks for letting us know.

Could you check ~/.local/share/sourcery and let me know what's there?
If there's a bin symlink, could you go to ~/.local/share/sourcery/bin , run sourcery--version and let me know the results?

**Comment by smilicev** [comment]
here you go. :)
```
./sourcery --version
sourcery, version 0.5.5
```

**Comment by Hellebore** [comment]
Thanks! So it's downloaded correctly but our plugin is failing to recognise that fact. I'll try and reproduce it.

**Comment by Hellebore** [comment]
I'm wondering if it's a locale issue. Could you tell me the output of running locale from the terminal?

**Comment by smilicev** [comment]
```
ontent-Length: 41
Content-Type: application/vscode-jsonrpc; charset=utf-8

{"jsonrpc": "2.0", "method": "heartbeat"}Content-Length: 41
Content-Type: application/vscode-jsonrpc; charset=utf-8

{"jsonrpc": "2.0", "method": "heartbeat"}Content-Length: 41
```
and it loops like that.

**Comment by Hellebore** [comment]
we've identified a possible fix and are testing it - will let you know how it goes.

**Comment by smilicev** [comment]
great. :)

**Comment by brendanator** [comment]
@smilicev This should be fixed with the latest version. If it doesn't work feel free to re-open

**Comment by smilicev** [comment]
it works. :) Thanks. :)
