### ISSUE TITLE
Failed to launch Sourcery service after updating from alpha

### ISSUE THREAD

**Issue by rbricheno** [sourceryai/public#19]
### Issue description or question

I was using Sourcery in alpha, but then didn't use it for a while. I recently updated the plugin to 0.1.2 (and updated my token) and found that the Sourcery service no longer starts, giving the following error:
```
2:47 PM	Failed to launch Sourcery service: login() missing 2 required positional arguments: 'plugin_version' and 'protocol_version'
```

### Sourcery Version

0.1.2

### Code editor or IDE name and version

Pycharm v2018.1.1

### OS name and version

Windows 10

**Comment by Hellebore** [comment]
Hi - could you try the following:
1. Open Pycharm and go to File> Settings > Plugins.
2. Click on the cog at the top right and choose 'Manage Plugin Repositories'
3. Remove the alpha channel entry (https://plugins.jetbrains.com/plugins/alpha/list )
4. Going back to the Plugins screen version 0.2.6 of Sourcery should now be available, so update to that and restart.

**Comment by rbricheno** [comment]
@Hellebore that worked perfectly, my problem is solved, thank you.
