### ISSUE TITLE
Following link to Sourcery Pro yields an error

### ISSUE THREAD

**Issue by kkinder** [sourceryai/public#20]
### Issue description or question

If you follow the link to Sourcery Pro, it'll open (Firefox for me) with a blank page:

https://sourcery.ai/subscribe/?product=pro

This exception is in the dev console:

```Error: "usePlans must be used within a PlansProvider"```

### Sourcery Version

N/A -- this is a web error.

**Comment by brendanator** [comment]
Thanks for the report, I'll look into it.

In the meantime you can visit https://sourcery.ai/pricing/ and select the `Try free beta` button there.

**Comment by brendanator** [comment]
This link should be fixed now. You may need to close and reopen Pycharm to see it.

Feel free to reopen this if you're still having problems
