### ISSUE TITLE
Sourcery plugin still recommends changes on deleted files

### ISSUE THREAD

**Issue by oserban** [sourceryai/public#4]
### Issue description or question

1. Scan an existing file so Sourcery reports an issue. Do not apply the refactorings
2. Rename the file (I think this also works with delete)
3. Sourcery still tracks the files even if it does not exist anymore

### Code editor or IDE name and version

Pycharm 2019.1.3

### OS name and version
Linux

**Comment by Hellebore** [comment]
Can reproduce with renaming the file, but not deleting. Will work on a fix - could you see if you can get this to happen with deleting the file?

**Comment by oserban** [comment]
You are right, initially I though I deleted the file but instead I renamed it. The delete operation does not leave suggestions behind, so you are right.

**Comment by brendanator** [comment]
Fixed in latest Pycharm alpha plugin version 0.0.10-SNAPSHOT
