### ISSUE TITLE
del from dictionary copy can be replaced by a list comprehension. 

### ISSUE THREAD

**Issue by AndrewLouw** [sourceryai/public#8]
### Issue description or question
This horrible way of iterating is not picked up:

    x0 = ['a', 'b']
    x1 = {'a': 1, 'b': 2, 'c': 3}
    for i in x1.copy():  # can't iterate over a variable that changes size
        if i not in x0:
            del x1[i]

when the much cleaner version is available.

    x0 = ['a', 'b']
    x1 = {'a': 1, 'b': 2, 'c': 3}
    x1 = {k: v for k, v in x1.copy().items() if k in x0}

### Code editor or IDE name and version

Pycharm 2019.1.3?

### OS name and version

Windows 10

**Comment by AndrewLouw** [comment]
ideally we'd also improve the version through a temporty variable
`x0 = ['a', 'b']
x1 = {'a': 1, 'b': 2, 'c': 3}
tmp = x1.copy()   # can't iterate over a variable that changes size
for i in tmp:
    if i not in x0:
        del x1[i]`

**Comment by Hellebore** [comment]
Interesting - we'll take a look into it.

**Comment by brendanator** [comment]
This should be implemented in the latest version of Sourcery
